### ISSUE TITLE
Testing HDFM in Windows

### ISSUE THREAD

**Issue by catmaps** [KYDronePilot/hdfm#17]
Hello,
I found your very interesting project in www.rtl-sdr.com. I am interested in getting the hardware to try it. However I wish to ensure I'd have sufficient HD signal. I am about 60 miles from the iHeart stations in Savannah and Augusta GA (it's flat country). My ZIP is 30439. Do you think I can pick up signal if I use one of the popular dongles from rtl-sdr.com? Or if best, which outdoor/rooftop antenna options would you suggest for my situation? 
I have a niche audience of followers who like to do things off-grid. In the past 5 years I personally helped over 700 people get started on portable Xowa for offline wikipedia and I have bridged pertinent feedback back to the Xowa developer to improve the program. More recently, I started doing the same with Offroad--an offline openstreetmaps for desktops. And I know my audience would be interested in your HDFM--especially if can made more friendly for Windows users.
In a prior issue, you mentioned plans were to refactor / compile for Windows? When will this be? I would be glad to test it for you, if I can be assured that I can get sufficient HD signal at 30439 and I am willing purchase outdoor equipment to do so.

**Comment by KYDronePilot** [comment]
Hi @catmaps,

Thank you for reaching out.

Regarding signal reception, I can't say for sure. For me, the furthest station I could receive is about 20 - 25 miles away. Granted, where I live is hilly and seems to suffer from bad signal reception in general.

My experience with antennas is limited, but I would say that if you got an outdoor antenna tuned for FM radio stations, you should be able to receive the stations in surrounding big cities.

Here are some I found on Amazon with reviews claiming to receive stations up to 60 miles away:

- <https://www.amazon.com/Winegard-HD-6010-HD-Radio-Antenna/dp/B001HKM1HM>
- <https://www.amazon.com/FM-Loop-Antenna-Outdoor-Attic-mount/dp/B006SLV25C/>
- <https://www.amazon.com/Antenna-High-Gain-Reception-Directional/dp/B01DWE9I9O/>

Signal reception does depend on a whole range of factors, so I can't say definitively whether or not you would be able to receive the stations with one of these antennas. If you can pick up the stations from a car though, I would be more confident that the antennas would work.

Regarding the SDR itself, I highly recommend the [one from rtl-sdr.com with the dipole antenna kit](https://www.amazon.com/RTL-SDR-Blog-RTL2832U-Software-Defined/dp/B011HVUEME/). If you just plan on using it for HD Radio, you could get the dongle by itself, but for an extra $10, the antenna kit is worth it (in my opinion), since there are so many other interesting things that can be done with an SDR. The dongle rtl-sdr.com sells is better than others (in my opinion), since it comes with a metal housing (helps dissipate heat better), has the larger SMA antenna connector, supports amplifiers (if needed in the future), and has been modified to allow it to receive lower-frequency, long-distance signals if desired.

Regarding Windows support, there is still a ways to go. I had started on updating the entire project a year ago, hoping to bring better support to all the major platforms and improve the user interface using Python and Python libraries. Unfortunately, I ran into issues that resulted from how old and unmaintained the Python `Tkinter` library was. A much better approach would be to rebuild the whole project using the Electron.js framework. I'm optimistic the rebuild could be completed by the end of this year, but I can't promise it.

Just to confirm, did you also reach out to me via phone recently? Don't want to send duplicate messages.

**Comment by KYDronePilot** [comment]
@catmaps The [latest release](https://github.com/KYDronePilot/hdfm/releases/latest) includes prebuilt binaries for Windows which run without any dependencies other than [nrsc5](https://github.com/theori-io/nrsc5). If you have any further questions, please post them here.
