### ISSUE TITLE
Album Artwork takes a while.

### ISSUE THREAD

**Issue by andrewfer000** [KYDronePilot/hdfm#18]
This program is AWESOME! Also I love the short and simple python code. The only issue I have is that the album artwork does not update until the song is almost over as if there was around a 2 minute delay. I do not know if this is because of the radio station or it's the program. But everything else works great! Here is a screenshot. You will noticed the song does not match the artwork.

Edit: Sometimes, the album art come in early but that is rare. Also, sometimes it does not update at all. It is probably the station.
![image](https://user-images.githubusercontent.com/9620913/102725492-1dcf4900-42e5-11eb-88cb-aef5c00d4256.png)

**Comment by andrewfer000** [comment]
In this new image, the Album art loaded a minute before the song and stayed loaded until the end but it stuck around well into the next song. Eventually it changed to the next song's artwork but it took almost 2 minutes. It's hard to tell if this is caused by the radio station, my SDR, setup, or the software. 
 
![image](https://user-images.githubusercontent.com/9620913/102726334-f16afb00-42eb-11eb-82e5-e2230933ca0d.png)

P.S. Since this is a technically "working" example feel free to use it as one of the program screenshots.

**Comment by KYDronePilot** [comment]
Thanks for your interest in this project!

Unfortunately, I believe this is mostly due to the radio station. I also had problems with artwork coming in about a minute early, and if the station had multiple HD channels (HD1, HD2, HD3, etc.) the artwork would jump back and forth between the songs playing on each channel.

`hdfm` is also slightly to blame. At the program level, `nrsc5` doesn't attach any info that can be used to determine what song or channel an artwork file is associated with. As a result, `hdfm` just looks for the latest jpg image that `nrsc5` dumped and displays it. It might be possible to make a modification to `nrsc5` to include this info when parsing the artwork, but I don't know a lot about how that project works.

Thank you for providing the screenshots; I will add one of them to the README.
